### ISSUE TITLE
license

### ISSUE THREAD

**Issue by cptaffe** [nf/reddit#1]
I've forked your repo and added an **MIT license**, since you don't currently license it under anything I believe US law defaults to your reservation of all rights. Github's terms may give me the right to fork it, but I don't know if I can license it under a license you don't approve. Do you approve of an MIT license, if not, name an appropriate license.

**Comment by nf** [comment]
It should be Apache 2.0 Licensed. Please amend your fork.

**Comment by nf** [comment]
Closed by a91daa62acf849823b11380a1b4937dc8ca69443

**Comment by cptaffe** [comment]
My apologies, prominent comment on the source code that I completely ignored.
